import type { LucideIcon } from 'lucide-react';
import {
  ArrowLeftRight,
  BanknoteArrowDown,
  BanknoteArrowUp,
  BookOpen,
  Boxes,
  ClipboardCheck,
  ClipboardList,
  Factory,
  FileSpreadsheet,
  PackageCheck,
  PackagePlus,
  Receipt,
  Scale,
  ScrollText,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Truck,
  UserCog,
  UsersRound,
  Wallet,
  Warehouse,
} from 'lucide-react';

import { hasAnyPermission, type DashboardPersona } from '@/lib/dashboard-access';
import { PERMISSIONS } from '@/lib/shared';

export interface DashboardShortcut {
  description: string;
  href: string;
  icon: LucideIcon;
  id: string;
  label: string;
  personas: DashboardPersona[];
  permissions: string[];
}

const DASHBOARD_SHORTCUTS: DashboardShortcut[] = [
  {
    description: 'Create branch sales and issue invoices from the sales desk.',
    href: '/sales',
    icon: ShoppingCart,
    id: 'new-sale',
    label: 'New Sale',
    personas: ['branch_manager', 'sales_lead', 'operations_manager', 'system_admin'],
    permissions: [PERMISSIONS.branchSales.create, PERMISSIONS.invoice.create, 'sales.create'],
  },
  {
    description: 'Post the receiving leg for branch or warehouse transfers.',
    href: '/inventory/transfers',
    icon: ArrowLeftRight,
    id: 'receive-stock-transfer',
    label: 'Receive Stock Transfer',
    personas: ['branch_manager', 'inventory_lead', 'operations_manager', 'system_admin'],
    permissions: ['inventory.transfer.complete', 'inventory.write', 'stock_transfer.approve'],
  },
  {
    description: 'Review branch quantities, availability, and valuation.',
    href: '/inventory/stock-balances',
    icon: Boxes,
    id: 'branch-stock',
    label: 'Branch Stock',
    personas: ['branch_manager', 'inventory_lead', 'operations_manager', 'system_admin'],
    permissions: [PERMISSIONS.inventory.read, 'inventory.read'],
  },
  {
    description: 'Trace the full stock movement ledger with references and journals.',
    href: '/inventory/stock-movements',
    icon: ScrollText,
    id: 'stock-ledger',
    label: 'Stock Movement Ledger',
    personas: ['branch_manager', 'inventory_lead', 'operations_manager', 'system_admin'],
    permissions: [PERMISSIONS.inventory.read, 'inventory.read', PERMISSIONS.reports.read],
  },
  {
    description: 'Record controlled stock gains and losses.',
    href: '/inventory/approvals',
    icon: ClipboardCheck,
    id: 'stock-adjustment',
    label: 'Stock Adjustment',
    personas: ['branch_manager', 'inventory_lead', 'operations_manager', 'system_admin'],
    permissions: [PERMISSIONS.inventory.adjust, 'inventory.write'],
  },
  {
    description: 'Enter and review branch operating expenses.',
    href: '/finance/expenses',
    icon: Receipt,
    id: 'branch-expenses',
    label: 'Branch Expenses',
    personas: ['branch_manager', 'finance_lead', 'operations_manager', 'system_admin'],
    permissions: [PERMISSIONS.branchExpense.create, PERMISSIONS.finance.read, 'finance.write'],
  },
  {
    description: 'Close the current branch shift with cash and variance control.',
    href: '/branches',
    icon: Wallet,
    id: 'close-shift',
    label: 'Close Shift',
    personas: ['branch_manager', 'operations_manager', 'system_admin'],
    permissions: [PERMISSIONS.branchShift.close, PERMISSIONS.branchShift.read, 'branch_shift.close'],
  },
  {
    description: 'Open printable invoice views for the current branch.',
    href: '/sales/invoices',
    icon: FileSpreadsheet,
    id: 'print-invoice',
    label: 'Print Invoice',
    personas: ['branch_manager', 'sales_lead', 'operations_manager', 'system_admin'],
    permissions: [PERMISSIONS.invoice.read, 'sales.read'],
  },
  {
    description: 'Raise a new purchase requisition for approval.',
    href: '/procurement/requisitions',
    icon: ClipboardList,
    id: 'new-requisition',
    label: 'New Requisition',
    personas: ['procurement_lead', 'operations_manager', 'system_admin'],
    permissions: [PERMISSIONS.purchaseRequisition.create, 'procurement.write'],
  },
  {
    description: 'Create and stage new purchase orders.',
    href: '/procurement/purchase-orders',
    icon: PackagePlus,
    id: 'new-purchase-order',
    label: 'New Purchase Order',
    personas: ['procurement_lead', 'operations_manager', 'system_admin'],
    permissions: [PERMISSIONS.purchaseOrder.create, 'procurement.write'],
  },
  {
    description: 'Review and approve submitted purchase orders.',
    href: '/procurement/purchase-orders',
    icon: PackageCheck,
    id: 'approve-purchase-order',
    label: 'Approve Purchase Order',
    personas: ['procurement_lead', 'operations_manager', 'system_admin'],
    permissions: [PERMISSIONS.purchaseOrder.approve, 'procurement.approve', 'approval.process'],
  },
  {
    description: 'Receive supplier deliveries against approved purchase orders.',
    href: '/procurement/goods-received',
    icon: Truck,
    id: 'receive-goods',
    label: 'Receive Goods',
    personas: ['procurement_lead', 'operations_manager', 'system_admin'],
    permissions: [PERMISSIONS.goodsReceived.create, 'procurement.write'],
  },
  {
    description: 'Review and post supplier invoices.',
    href: '/procurement/invoices',
    icon: Receipt,
    id: 'supplier-invoice',
    label: 'Supplier Invoice',
    personas: ['procurement_lead', 'finance_lead', 'operations_manager', 'system_admin'],
    permissions: [PERMISSIONS.finance.read, 'procurement.read', 'supplier_invoice.read'],
  },
  {
    description: 'Process supplier settlements and payment records.',
    href: '/procurement/payments',
    icon: BanknoteArrowDown,
    id: 'supplier-payment',
    label: 'Supplier Payment',
    personas: ['procurement_lead', 'finance_lead', 'operations_manager', 'system_admin'],
    permissions: [PERMISSIONS.finance.read, 'finance.write', 'supplier_payment.read'],
  },
  {
    description: 'Capture a new production order by product number.',
    href: '/production/orders/new',
    icon: Factory,
    id: 'create-production-order',
    label: 'Create Production Order',
    personas: ['production_manager', 'operations_manager', 'system_admin'],
    permissions: [PERMISSIONS.productionBatch.create, 'production.write'],
  },
  {
    description: 'Maintain BOM and production recipe structures.',
    href: '/production/recipes',
    icon: BookOpen,
    id: 'create-bom',
    label: 'Create BOM',
    personas: ['production_manager', 'operations_manager', 'system_admin'],
    permissions: [PERMISSIONS.productionRecipe.manage, 'production.write'],
  },
  {
    description: 'Issue raw materials to released production orders.',
    href: '/production/orders',
    icon: Warehouse,
    id: 'issue-materials',
    label: 'Issue Materials',
    personas: ['production_manager', 'operations_manager', 'system_admin'],
    permissions: [PERMISSIONS.productionBatch.read, 'production.write'],
  },
  {
    description: 'Receive accepted finished goods and cost the run.',
    href: '/production/orders',
    icon: PackageCheck,
    id: 'receive-finished-goods',
    label: 'Receive Finished Goods',
    personas: ['production_manager', 'operations_manager', 'system_admin'],
    permissions: [PERMISSIONS.productionBatch.read, 'production.write'],
  },
  {
    description: 'Record wastage and production losses.',
    href: '/production/wastage',
    icon: ClipboardCheck,
    id: 'record-wastage',
    label: 'Record Wastage',
    personas: ['production_manager', 'operations_manager', 'system_admin'],
    permissions: [PERMISSIONS.productionBatch.read, 'production.write', 'production.wastage.write'],
  },
  {
    description: 'Review accepted-unit cost and output performance.',
    href: '/production/reports',
    icon: FileSpreadsheet,
    id: 'production-cost-report',
    label: 'Production Cost Report',
    personas: ['production_manager', 'operations_manager', 'system_admin'],
    permissions: [PERMISSIONS.productionBatch.read, PERMISSIONS.reports.read, 'production.read'],
  },
  {
    description: 'Create manual journal entries.',
    href: '/finance/journals',
    icon: FileSpreadsheet,
    id: 'new-journal',
    label: 'New Journal',
    personas: ['finance_lead', 'system_admin'],
    permissions: [PERMISSIONS.finance.manage, 'finance.write', 'finance.gl.create'],
  },
  {
    description: 'Load opening balances for controlled cutover.',
    href: '/finance/opening-balances',
    icon: ClipboardList,
    id: 'opening-balances',
    label: 'Opening Balances',
    personas: ['finance_lead', 'system_admin'],
    permissions: [PERMISSIONS.finance.read, 'finance.gl.post'],
  },
  {
    description: 'Maintain the official chart of accounts.',
    href: '/finance/chart-of-accounts',
    icon: BookOpen,
    id: 'chart-of-accounts',
    label: 'Chart of Accounts',
    personas: ['finance_lead', 'system_admin'],
    permissions: [PERMISSIONS.finance.read, PERMISSIONS.finance.manage],
  },
  {
    description: 'Run the trial balance for the current period.',
    href: '/finance/reports',
    icon: Scale,
    id: 'trial-balance',
    label: 'Trial Balance',
    personas: ['finance_lead', 'system_admin'],
    permissions: [PERMISSIONS.finance.read, PERMISSIONS.reports.read],
  },
  {
    description: 'Run the income statement from posted journals.',
    href: '/finance/reports',
    icon: FileSpreadsheet,
    id: 'income-statement',
    label: 'Income Statement',
    personas: ['finance_lead', 'system_admin'],
    permissions: [PERMISSIONS.finance.read, PERMISSIONS.reports.read],
  },
  {
    description: 'Run the balance sheet from posted journals.',
    href: '/finance/reports',
    icon: FileSpreadsheet,
    id: 'balance-sheet',
    label: 'Balance Sheet',
    personas: ['finance_lead', 'system_admin'],
    permissions: [PERMISSIONS.finance.read, PERMISSIONS.reports.read],
  },
  {
    description: 'Review and reconcile bank activity.',
    href: '/finance/bank-accounts',
    icon: BanknoteArrowUp,
    id: 'bank-reconciliation',
    label: 'Bank Reconciliation',
    personas: ['finance_lead', 'system_admin'],
    permissions: [PERMISSIONS.finance.read, 'bank.read'],
  },
  {
    description: 'Capture and monitor customer receipts.',
    href: '/sales/payments',
    icon: BanknoteArrowUp,
    id: 'customer-receipts',
    label: 'Customer Receipts',
    personas: ['finance_lead', 'system_admin'],
    permissions: [PERMISSIONS.finance.read, PERMISSIONS.payment.create, 'sales.read'],
  },
  {
    description: 'Capture supplier payment execution.',
    href: '/procurement/payments',
    icon: BanknoteArrowDown,
    id: 'supplier-payments-finance',
    label: 'Supplier Payments',
    personas: ['finance_lead', 'system_admin'],
    permissions: [PERMISSIONS.finance.read, 'supplier_payment.read', 'finance.write'],
  },
  {
    description: 'Manage users and user access.',
    href: '/settings/users',
    icon: UsersRound,
    id: 'users',
    label: 'Users',
    personas: ['system_admin'],
    permissions: [PERMISSIONS.user.manage, PERMISSIONS.settings.manage],
  },
  {
    description: 'Maintain roles and role permissions.',
    href: '/settings/roles',
    icon: ShieldCheck,
    id: 'roles',
    label: 'Roles',
    personas: ['system_admin'],
    permissions: [PERMISSIONS.settings.manage, 'manage_roles'],
  },
  {
    description: 'Review branch and warehouse access assignments.',
    href: '/branches',
    icon: ArrowLeftRight,
    id: 'branch-assignments',
    label: 'Branch Assignments',
    personas: ['system_admin'],
    permissions: [PERMISSIONS.settings.manage, 'branches.read'],
  },
  {
    description: 'Maintain warehouse structures and branch links.',
    href: '/inventory/warehouses',
    icon: Warehouse,
    id: 'warehouses',
    label: 'Warehouses',
    personas: ['system_admin'],
    permissions: [PERMISSIONS.settings.manage, PERMISSIONS.inventory.read],
  },
  {
    description: 'Review ERP account mapping configuration.',
    href: '/finance/chart-of-accounts',
    icon: BookOpen,
    id: 'account-mappings',
    label: 'Account Mappings',
    personas: ['system_admin'],
    permissions: [PERMISSIONS.settings.manage, PERMISSIONS.finance.read],
  },
  {
    description: 'Inspect operational and security audit trails.',
    href: '/settings/audit-logs',
    icon: ScrollText,
    id: 'audit-logs',
    label: 'Audit Logs',
    personas: ['system_admin'],
    permissions: [PERMISSIONS.auditLog.read, PERMISSIONS.settings.manage],
  },
  {
    description: 'Open administrative settings and platform controls.',
    href: '/settings',
    icon: Settings,
    id: 'system-settings',
    label: 'System Settings',
    personas: ['system_admin'],
    permissions: [PERMISSIONS.settings.manage],
  },
];

export function resolveDashboardShortcuts(
  persona: DashboardPersona,
  permissions: readonly string[],
) {
  return DASHBOARD_SHORTCUTS.filter((shortcut) => (
    shortcut.personas.includes(persona) && hasAnyPermission(permissions, shortcut.permissions)
  ));
}
