import assert from 'node:assert/strict';
import test from 'node:test';

import { createBrandedPdfDocument } from '../src/lib/pdf';
import { REPORT_DEFINITIONS, findReportDefinition, toReportCsv, validateReportDateRange } from '../src/lib/reporting';

test('report registry exposes inventory valuation definition', () => {
  const definition = findReportDefinition('inventory', 'valuation');
  assert.ok(definition);
  assert.equal(definition?.requiredPermission, 'view_cost');
});

test('report definitions include multiple categories', () => {
  const categories = new Set(REPORT_DEFINITIONS.map((definition) => definition.category));
  assert.ok(categories.has('inventory'));
  assert.ok(categories.has('finance'));
  assert.ok(categories.has('audit'));
});

test('validateReportDateRange rejects reversed dates', () => {
  assert.throws(() => validateReportDateRange('2026-06-20', '2026-06-10'));
});

test('toReportCsv includes metadata and row headers', () => {
  const csv = toReportCsv({
    filters: { branchId: 'branch-1' },
    generatedAt: '2026-06-13T08:00:00.000Z',
    generatedBy: 'AQI-20260001',
    rows: [{ item: 'Cone Mix', qty: 12, value: 33.5 }],
    title: 'Inventory Valuation Report',
  });

  assert.match(csv, /Report Title,Inventory Valuation Report/);
  assert.match(csv, /Generated By,AQI-20260001/);
  assert.match(csv, /item,qty,value/);
  assert.match(csv, /Cone Mix,12,33.5/);
});

test('createBrandedPdfDocument includes branded header, footer, and table content', () => {
  const pdf = Buffer.from(createBrandedPdfDocument({
    generatedAt: '2026-07-16T08:00:00.000Z',
    generatedBy: 'AQI-20260001',
    metadata: [
      { label: 'Date Range', value: '2026-07-10 to 2026-07-16' },
      { label: 'Warehouse', value: 'Main Warehouse' },
    ],
    summary: [
      { label: 'Total Warehouse Value', value: '$0.00' },
    ],
    table: {
      columns: [
        { header: 'Item', key: 'item', width: 180 },
        { header: 'Warehouse', key: 'warehouse', width: 140 },
        { align: 'right', header: 'Qty', key: 'qty', width: 60 },
        { align: 'right', header: 'Unit Cost', key: 'unit_cost', width: 80 },
        { align: 'right', header: 'Total Value', key: 'total_value', width: 90 },
      ],
      rows: [
        { item: 'Vanilla Base', qty: 0, total_value: 0, unit_cost: 0, warehouse: 'Main Warehouse' },
      ],
      title: 'Report Data',
    },
    title: 'Inventory Valuation Report',
  })).toString('latin1');

  assert.match(pdf, /Absolute Ice Cream ERP/);
  assert.match(pdf, /Inventory Valuation Report/);
  assert.match(pdf, /Powered by Nexatech/);
  assert.match(pdf, /Report Data/);
  assert.match(pdf, /\/Subtype \/Image/);
});
