import assert from 'node:assert/strict';
import test from 'node:test';

import { REPORT_DEFINITIONS, findReportDefinition, toReportCsv, validateReportDateRange } from '../src/lib/reporting';

test('report registry exposes inventory valuation definition', () => {
  const definition = findReportDefinition('inventory', 'valuation');
  assert.ok(definition);
  assert.equal(definition?.requiredPermission, 'view_cost');
});

test('report definitions include multiple categories', () => {
  const categories = new Set(REPORT_DEFINITIONS.map((definition) => definition.category));
  assert.ok(categories.has('inventory'));
  assert.ok(categories.has('finance'));
  assert.ok(categories.has('audit'));
});

test('validateReportDateRange rejects reversed dates', () => {
  assert.throws(() => validateReportDateRange('2026-06-20', '2026-06-10'));
});

test('toReportCsv includes metadata and row headers', () => {
  const csv = toReportCsv({
    filters: { branchId: 'branch-1' },
    generatedAt: '2026-06-13T08:00:00.000Z',
    generatedBy: 'AQI-20260001',
    rows: [{ item: 'Cone Mix', qty: 12, value: 33.5 }],
    title: 'Inventory Valuation Report',
  });

  assert.match(csv, /Report Title,Inventory Valuation Report/);
  assert.match(csv, /Generated By,AQI-20260001/);
  assert.match(csv, /item,qty,value/);
  assert.match(csv, /Cone Mix,12,33.5/);
});
