"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const strict_1 = __importDefault(require("node:assert/strict"));
const node_test_1 = __importDefault(require("node:test"));
const pdf_1 = require("../src/lib/pdf");
const reporting_1 = require("../src/lib/reporting");
(0, node_test_1.default)('report registry exposes inventory valuation definition', () => {
    const definition = (0, reporting_1.findReportDefinition)('inventory', 'valuation');
    strict_1.default.ok(definition);
    strict_1.default.equal(definition?.requiredPermission, 'view_cost');
});
(0, node_test_1.default)('report definitions include multiple categories', () => {
    const categories = new Set(reporting_1.REPORT_DEFINITIONS.map((definition) => definition.category));
    strict_1.default.ok(categories.has('inventory'));
    strict_1.default.ok(categories.has('finance'));
    strict_1.default.ok(categories.has('audit'));
});
(0, node_test_1.default)('validateReportDateRange rejects reversed dates', () => {
    strict_1.default.throws(() => (0, reporting_1.validateReportDateRange)('2026-06-20', '2026-06-10'));
});
(0, node_test_1.default)('toReportCsv includes metadata and row headers', () => {
    const csv = (0, reporting_1.toReportCsv)({
        filters: { branchId: 'branch-1' },
        generatedAt: '2026-06-13T08:00:00.000Z',
        generatedBy: 'AQI-20260001',
        rows: [{ item: 'Cone Mix', qty: 12, value: 33.5 }],
        title: 'Inventory Valuation Report',
    });
    strict_1.default.match(csv, /Report Title,Inventory Valuation Report/);
    strict_1.default.match(csv, /Generated By,AQI-20260001/);
    strict_1.default.match(csv, /item,qty,value/);
    strict_1.default.match(csv, /Cone Mix,12,33.5/);
});
(0, node_test_1.default)('createBrandedPdfDocument includes branded header, footer, and table content', () => {
    const pdf = Buffer.from((0, pdf_1.createBrandedPdfDocument)({
        generatedAt: '2026-07-16T08:00:00.000Z',
        generatedBy: 'AQI-20260001',
        metadata: [
            { label: 'Date Range', value: '2026-07-10 to 2026-07-16' },
            { label: 'Warehouse', value: 'Main Warehouse' },
        ],
        summary: [
            { label: 'Total Warehouse Value', value: '$0.00' },
        ],
        table: {
            columns: [
                { header: 'Item', key: 'item', width: 180 },
                { header: 'Warehouse', key: 'warehouse', width: 140 },
                { align: 'right', header: 'Qty', key: 'qty', width: 60 },
                { align: 'right', header: 'Unit Cost', key: 'unit_cost', width: 80 },
                { align: 'right', header: 'Total Value', key: 'total_value', width: 90 },
            ],
            rows: [
                { item: 'Vanilla Base', qty: 0, total_value: 0, unit_cost: 0, warehouse: 'Main Warehouse' },
            ],
            title: 'Report Data',
        },
        title: 'Inventory Valuation Report',
    })).toString('latin1');
    strict_1.default.match(pdf, /Absolute Ice Cream ERP/);
    strict_1.default.match(pdf, /Inventory Valuation Report/);
    strict_1.default.match(pdf, /Powered by Nexatech/);
    strict_1.default.match(pdf, /Report Data/);
    strict_1.default.match(pdf, /\/Subtype \/Image/);
});
