import { NextResponse } from 'next/server';

import { can, forbidden, getAuthContext, serverError, unauthorized } from '@/lib/api-auth';
import { createPlainTextPdf } from '@/lib/pdf';
import { recordReportExport, recordReportRun } from '@/lib/reporting-server';

function titleCase(value: string) {
  return value
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

function formatCell(value: unknown) {
  if (value === null || value === undefined) return '';
  if (typeof value === 'number') return Number.isInteger(value) ? String(value) : value.toFixed(3);
  if (typeof value === 'object') return JSON.stringify(value);
  return String(value);
}

export async function GET(request: Request) {
  const ctx = await getAuthContext(request);
  if (!ctx) return unauthorized();
  if (!can(ctx, 'export', 'reports.read')) return forbidden();

  try {
    const url = new URL(request.url);
    const reportType = url.searchParams.get('reportType') ?? 'report';
    const title = titleCase(reportType);
    const reportUrl = new URL('/api/reports', url.origin);
    reportUrl.search = url.searchParams.toString();

    const reportResponse = await fetch(reportUrl, {
      headers: {
        cookie: request.headers.get('cookie') ?? '',
      },
      method: 'GET',
    });

    const payload = await reportResponse.json().catch(() => null);
    if (!reportResponse.ok) {
      return serverError((payload as { error?: string } | null)?.error ?? 'Failed to generate report PDF.');
    }

    const report = payload as {
      chart?: Array<Record<string, unknown>>;
      data?: Array<Record<string, unknown>>;
      summary?: Record<string, unknown>;
    };
    const data = report.data ?? [];
    const summary = report.summary ?? {};
    const filters = Object.fromEntries(url.searchParams.entries());
    const lines: string[] = [
      `Report: ${title}`,
      `Generated: ${new Date().toISOString()}`,
      `Generated By: ${ctx.workId}`,
      `Date Range: ${url.searchParams.get('startDate') ?? 'N/A'} to ${url.searchParams.get('endDate') ?? 'N/A'}`,
      '',
      'Summary',
    ];

    if (Object.keys(summary).length === 0) {
      lines.push('No summary values returned.');
    } else {
      for (const [key, value] of Object.entries(summary)) {
        lines.push(`${titleCase(key)}: ${formatCell(value)}`);
      }
    }

    lines.push('', 'Rows');
    if (data.length === 0) {
      lines.push('No rows returned for the selected filters.');
    } else {
      const columns = Object.keys(data[0] ?? {});
      lines.push(columns.map((column) => titleCase(column)).join(' | '));
      lines.push('-'.repeat(Math.min(120, columns.join(' | ').length + 12)));
      for (const row of data.slice(0, 200)) {
        lines.push(columns.map((column) => formatCell(row[column])).join(' | '));
      }
      if (data.length > 200) {
        lines.push('', `Output truncated to first 200 rows of ${data.length}.`);
      }
    }

    const fileName = `${reportType}-${new Date().toISOString().slice(0, 10)}.pdf`;
    const pdf = createPlainTextPdf(lines, { title: `${title} Export` });

    await Promise.all([
      recordReportRun({
        branchId: ctx.branchId,
        category: 'general',
        filters,
        format: 'PDF',
        reportType,
        status: 'COMPLETED',
        userProfileId: ctx.userId,
      }),
      recordReportExport({
        branchId: ctx.branchId,
        category: 'general',
        fileName,
        filters,
        format: 'PDF',
        organizationId: ctx.organizationId,
        reportType,
        userProfileId: ctx.userId,
      }),
    ]);

    return new NextResponse(Buffer.from(pdf), {
      headers: {
        'Content-Disposition': `attachment; filename="${fileName}"`,
        'Content-Type': 'application/pdf',
      },
    });
  } catch (error) {
    return serverError(error instanceof Error ? error.message : 'Failed to export report PDF.');
  }
}
