const AUTH = {
  LOGIN: '/api/auth/login',
  REGISTER: '/api/auth/register',
  ME: '/api/auth/me',
  LOGOUT: '/api/auth/logout',
  ROLES: '/api/auth/roles'
} as const;

export const API_ROUTES = {
  ...AUTH,

  SUPPLIERS: '/api/procurement/suppliers',
  SUPPLIER: (id: string) => `/api/procurement/suppliers/${id}`,
  SUPPLIERS_META: '/api/procurement/suppliers/meta',
  SUPPLIER_PURCHASE_HISTORY: (id: string) => `/api/procurement/suppliers/${id}/purchase-history`,
  REQUISITIONS: '/api/procurement/requisitions',
  REQUISITION: (id: string) => `/api/procurement/requisitions/${id}`,
  PURCHASE_ORDERS: '/api/procurement/purchase-orders',
  PURCHASE_ORDER: (id: string) => `/api/procurement/purchase-orders/${id}`,
  GRNS: '/api/procurement/grns',
  GRN: (id: string) => `/api/procurement/grns/${id}`,

  ITEMS: '/api/inventory/items',
  ITEM: (id: string) => `/api/inventory/items/${id}`,
  WAREHOUSES: '/api/inventory/warehouses',
  STOCK_BALANCES: '/api/inventory/stock-balances',
  STOCK_MOVEMENTS: '/api/inventory/stock-movements',
  TRANSFERS: '/api/inventory/transfers',
  TRANSFER: (id: string) => `/api/inventory/transfers/${id}`,
  LOW_STOCK: '/api/inventory/low-stock',
  EXPIRING: '/api/inventory/expiring',

  RECIPES: '/api/production/recipes',
  RECIPE: (id: string) => `/api/production/recipes/${id}`,
  BATCHES: '/api/production/batches',
  BATCH: (id: string) => `/api/production/batches/${id}`,
  BATCH_REQUEST_MATERIALS: (id: string) => `/api/production/batches/${id}/request-materials`,
  BATCH_APPROVE_MATERIALS: (id: string) => `/api/production/batches/${id}/approve-materials`,
  BATCH_RESERVE: (id: string) => `/api/production/batches/${id}/reserve-materials`,
  BATCH_START: (id: string) => `/api/production/batches/${id}/start`,
  BATCH_SUBMIT_QUALITY: (id: string) => `/api/production/batches/${id}/submit-quality`,
  BATCH_QUALITY: (id: string) => `/api/production/batches/${id}/quality-result`,
  BATCH_CLOSE: (id: string) => `/api/production/batches/${id}/close`,
  BATCH_CANCEL: (id: string) => `/api/production/batches/${id}/cancel`,
  BATCH_ASSIGN_WORKERS: (id: string) => `/api/production/batches/${id}/assign-workers`,
  MATERIAL_REQUESTS: '/api/production/material-requests',
  MATERIAL_REQUEST: (id: string) => `/api/production/material-requests/${id}`,
  MATERIAL_REQUEST_APPROVE: (id: string) => `/api/production/material-requests/${id}/approve`,
  MATERIAL_REQUEST_ISSUE: (id: string) => `/api/production/material-requests/${id}/issue`,
  QUALITY_CHECKS: '/api/production/quality-checks',
  WASTAGE: '/api/production/wastage',
  SHIFT_REPORTS: '/api/production/shift-reports',
  PRODUCTION_DASHBOARD: '/api/production/dashboard',

  BRANCHES: '/api/branches',
  BRANCH: (id: string) => `/api/branches/${id}`,
  BRANCH_DASHBOARD: (id: string) => `/api/branches/${id}/dashboard`,
  BRANCH_USERS: (id: string) => `/api/branches/${id}/users`,
  BRANCH_STOCK: (id: string) => `/api/branches/${id}/stock`,
  BRANCH_STOCK_LEDGER: (id: string) => `/api/branches/${id}/stock-ledger`,
  BRANCH_STOCK_RECEIPTS: (id: string) => `/api/branches/${id}/stock-receipts`,
  BRANCH_SHIFTS: (id: string) => `/api/branches/${id}/shifts`,
  BRANCH_SHIFTS_OPEN: (id: string) => `/api/branches/${id}/shifts/open`,
  BRANCH_SALES_V2: (id: string) => `/api/branches/${id}/sales`,
  BRANCH_CUSTOMERS: (id: string) => `/api/branches/${id}/customers`,
  BRANCH_PAYMENTS: (id: string) => `/api/branches/${id}/payments`,
  BRANCH_EXPENSES_V2: (id: string) => `/api/branches/${id}/expenses`,
  BRANCH_STOCK_COUNTS: (id: string) => `/api/branches/${id}/stock-counts`,
  BRANCH_RETURNS: (id: string) => `/api/branches/${id}/returns`,
  BRANCH_REPORT_DAILY_SALES: '/api/branches/reports/daily-sales',
  BRANCH_REPORT_SHIFT: '/api/branches/reports/shift',
  BRANCH_REPORT_STOCK_MOVEMENT: '/api/branches/reports/stock-movement',
  BRANCH_REPORT_STOCK_BALANCE: '/api/branches/reports/stock-balance',
  BRANCH_REPORT_CASH_UP: '/api/branches/reports/cash-up',
  BRANCH_REPORT_EXPENSES: '/api/branches/reports/expenses',
  BRANCH_REPORT_CREDIT_SALES: '/api/branches/reports/credit-sales',
  BRANCH_REPORT_RETURNS: '/api/branches/reports/returns',
  BRANCH_REPORT_VARIANCE: '/api/branches/reports/variance',
  BRANCH_REPORT_PROFITABILITY: '/api/branches/reports/profitability',
  BRANCH_EXPORT: (reportType: string) => `/api/branches/export/${reportType}`,
  BRANCH_IMPORT_BRANCHES: '/api/branches/import/branches',
  BRANCH_IMPORT_CUSTOMERS: '/api/branches/import/customers',
  BRANCH_IMPORT_OPENING_BALANCES: '/api/branches/import/opening-balances',
  BRANCH_SALES: (branchId: string) => `/api/branch-operations/${branchId}/sales`,
  BRANCH_SALE: (branchId: string, id: string) => `/api/branch-operations/${branchId}/sales/${id}`,
  BRANCH_EXPENSES: (branchId: string) => `/api/branch-operations/${branchId}/expenses`,
  BRANCH_SHIFT_CLOSES: (branchId: string) => `/api/branch-operations/${branchId}/shift-closes`,
  BRANCH_SHIFT_CLOSE: (branchId: string, id: string) => `/api/branch-operations/${branchId}/shift-closes/${id}`,
  BRANCH_SHIFT_CLOSE_SUBMIT: (branchId: string, id: string) =>
    `/api/branch-operations/${branchId}/shift-closes/${id}/submit`,
  BRANCH_SHIFT_CLOSE_APPROVE: (branchId: string, id: string) =>
    `/api/branch-operations/${branchId}/shift-closes/${id}/approve`,
  BRANCH_SHIFT_CLOSE_REJECT: (branchId: string, id: string) =>
    `/api/branch-operations/${branchId}/shift-closes/${id}/reject`,

  CUSTOMERS: '/api/sales/customers',
  CUSTOMER: (id: string) => `/api/sales/customers/${id}`,
  CUSTOMER_ACTIVATE: (id: string) => `/api/sales/customers/${id}/activate`,
  CUSTOMER_DEACTIVATE: (id: string) => `/api/sales/customers/${id}/deactivate`,
  CUSTOMER_BALANCE: (id: string) => `/api/sales/customers/${id}/balance`,
  CUSTOMER_LEDGER: (id: string) => `/api/sales/customers/${id}/ledger`,
  QUOTATIONS: '/api/sales/quotations',
  QUOTATION: (id: string) => `/api/sales/quotations/${id}`,
  QUOTATION_CONVERT: (id: string) => `/api/sales/quotations/${id}/convert-to-order`,
  SALES_ORDERS: '/api/sales/orders',
  SALES_ORDER: (id: string) => `/api/sales/orders/${id}`,
  SALES_ORDER_CONFIRM: (id: string) => `/api/sales/orders/${id}/confirm`,
  SALES_ORDER_CANCEL: (id: string) => `/api/sales/orders/${id}/cancel`,
  DELIVERY_NOTES: '/api/sales/delivery-notes',
  DELIVERY_NOTE: (id: string) => `/api/sales/delivery-notes/${id}`,
  INVOICES: '/api/sales/invoices',
  INVOICE: (id: string) => `/api/sales/invoices/${id}`,
  INVOICE_PAYMENT: (id: string) => `/api/sales/invoices/${id}/payment`,
  INVOICE_PDF: (id: string) => `/api/sales/invoices/${id}/pdf`,
  PAYMENTS: '/api/sales/payments',
  SALES_CUSTOMER_GROUPS: '/api/sales/customer-groups',
  SALES_PRICES: '/api/sales/prices',
  SALES_PRICE: (id: string) => `/api/sales/prices/${id}`,
  SALES_DISCOUNTS: '/api/sales/discounts',
  SALES_DISCOUNT: (id: string) => `/api/sales/discounts/${id}`,
  SALES_DISCOUNT_APPROVE: (id: string) => `/api/sales/discounts/${id}/approve`,
  SALES_QUOTATION_APPROVE: (id: string) => `/api/sales/quotations/${id}/approve`,
  SALES_ORDER_APPROVE: (id: string) => `/api/sales/orders/${id}/approve`,
  SALES_INVOICE_APPROVE: (id: string) => `/api/sales/invoices/${id}/approve`,
  SALES_INVOICE_CANCEL: (id: string) => `/api/sales/invoices/${id}/cancel`,
  SALES_DISPATCHES: '/api/sales/dispatches',
  SALES_DISPATCH: (id: string) => `/api/sales/dispatches/${id}`,
  SALES_DISPATCH_POST: (id: string) => `/api/sales/dispatches/${id}/post`,
  SALES_DISPATCH_CANCEL: (id: string) => `/api/sales/dispatches/${id}/cancel`,
  SALES_RETURNS: '/api/sales/returns',
  SALES_RETURN: (id: string) => `/api/sales/returns/${id}`,
  SALES_RETURN_QC: (id: string) => `/api/sales/returns/${id}/qc`,
  SALES_RETURN_APPROVE: (id: string) => `/api/sales/returns/${id}/approve`,
  SALES_CREDIT_NOTES: '/api/sales/credit-notes',
  SALES_CREDIT_NOTE: (id: string) => `/api/sales/credit-notes/${id}`,
  SALES_CREDIT_NOTE_APPROVE: (id: string) => `/api/sales/credit-notes/${id}/approve`,
  SALES_JOURNALS: '/api/sales/journals',
  SALES_REPORT_DAILY: '/api/sales/reports/daily-sales',
  SALES_REPORT_CUSTOMER: '/api/sales/reports/customer-sales',
  SALES_REPORT_PRODUCT: '/api/sales/reports/product-sales',
  SALES_REPORT_BRANCH: '/api/sales/reports/branch-sales',
  SALES_REPORT_AGEING: '/api/sales/reports/invoice-ageing',
  SALES_REPORT_CREDIT_LIMITS: '/api/sales/reports/credit-limits',
  SALES_REPORT_DISPATCHES: '/api/sales/reports/dispatches',
  SALES_REPORT_RETURNS: '/api/sales/reports/returns',
  SALES_REPORT_JOURNALS: '/api/sales/reports/journals',
  SALES_EXPORT: (reportType: string) => `/api/sales/export/${reportType}`,
  SALES_IMPORT_CUSTOMERS: '/api/sales/import/customers',
  SALES_IMPORT_PRICES: '/api/sales/import/prices',
  SALES_IMPORT_CUSTOMER_BALANCES: '/api/sales/import/customer-balances',

  ACCOUNTS: '/api/finance/accounts',
  ACCOUNT: (id: string) => `/api/finance/accounts/${id}`,
  BANK_ACCOUNTS: '/api/finance/bank-accounts',
  FINANCE_CHART_OF_ACCOUNTS: '/api/finance/chart-of-accounts',
  FINANCE_FISCAL_PERIODS: '/api/finance/fiscal-periods',
  FINANCE_EXPENSES: '/api/finance/expenses',
  FINANCE_BANK_TRANSACTIONS: '/api/finance/bank-transactions',
  FINANCE_CASH: '/api/finance/cash',
  CASH_ACCOUNTS: '/api/finance/cash-accounts',
  JOURNALS: '/api/finance/journals',
  JOURNAL: (id: string) => `/api/finance/journals/${id}`,
  JOURNAL_SUBMIT: (id: string) => `/api/finance/journals/${id}/submit`,
  JOURNAL_APPROVE: (id: string) => `/api/finance/journals/${id}/approve`,
  JOURNAL_POST: (id: string) => `/api/finance/journals/${id}/post`,
  JOURNAL_REVERSE: (id: string) => `/api/finance/journals/${id}/reverse`,
  FINANCE_SALES_JOURNALS: '/api/finance/sales-journals',
  FINANCE_PURCHASE_JOURNALS: '/api/finance/purchase-journals',
  PETTY_CASH_REQUESTS: '/api/finance/petty-cash',
  PETTY_CASH_APPROVE: (id: string) => `/api/finance/petty-cash/${id}/approve`,
  BUDGETS: '/api/finance/budgets',
  BUDGET: (id: string) => `/api/finance/budgets/${id}`,
  BUDGET_APPROVE: (id: string) => `/api/finance/budgets/${id}/approve`,
  FIXED_ASSETS: '/api/finance/fixed-assets',
  FIXED_ASSET: (id: string) => `/api/finance/fixed-assets/${id}`,
  FIXED_ASSET_DEPRECIATE: (id: string) => `/api/finance/fixed-assets/${id}/depreciate`,
  FINANCE_ACCOUNTS_RECEIVABLE: '/api/finance/accounts-receivable',
  FINANCE_ACCOUNTS_PAYABLE: '/api/finance/accounts-payable',
  FINANCE_TAX_CODES: '/api/finance/tax-codes',
  FINANCE_TAX_TRANSACTIONS: '/api/finance/tax-transactions',
  FINANCE_REPORT_TRIAL_BALANCE: '/api/finance/reports/trial-balance',
  FINANCE_REPORT_PROFIT_AND_LOSS: '/api/finance/reports/profit-and-loss',
  FINANCE_REPORT_BALANCE_SHEET: '/api/finance/reports/balance-sheet',
  FINANCE_REPORT_RATIOS: '/api/finance/reports/ratios',
  FINANCE_REPORT_CASH_FLOW: '/api/finance/reports/cash-flow',
  FINANCE_REPORT_GENERAL_LEDGER: '/api/finance/reports/general-ledger',
  FINANCE_REPORT_RECEIVABLES_AGEING: '/api/finance/reports/receivables-ageing',
  FINANCE_REPORT_PAYABLES_AGEING: '/api/finance/reports/payables-ageing',
  FINANCE_REPORT_RECEIVABLES: '/api/finance/reports/receivables',
  FINANCE_REPORT_PAYABLES: '/api/finance/reports/payables',
  FINANCE_REPORT_BUDGET_VARIANCE: '/api/finance/reports/budget-variance',
  FINANCE_REPORT_BRANCH_PROFITABILITY: '/api/finance/reports/branch-profitability',
  FINANCE_REPORT_BRANCH_COSTING: '/api/finance/reports/branch-costing',
  FINANCE_REPORT_PRODUCTION_COSTING: '/api/finance/reports/production-costing',
  FINANCE_REPORT_INVENTORY_VALUATION: '/api/finance/reports/inventory-valuation',
  FINANCE_REPORT_COST_OF_GOODS_SOLD: '/api/finance/reports/cost-of-goods-sold',
  FINANCE_REPORT_TAX: '/api/finance/reports/tax',
  FINANCE_EXPORT: (reportType: string) => `/api/finance/export/${reportType}`,
  FINANCE_IMPORT_CHART_OF_ACCOUNTS: '/api/finance/import/chart-of-accounts',
  FINANCE_IMPORT_BUDGETS: '/api/finance/import/budgets',
  FINANCE_IMPORT_FIXED_ASSETS: '/api/finance/import/fixed-assets',
  FINANCE_IMPORT_BANK_ACCOUNTS: '/api/finance/import/bank-accounts',
  FINANCE_IMPORT_OPENING_BALANCES: '/api/finance/import/opening-balances',

  EMPLOYEES: '/api/hr/employees',
  EMPLOYEE: (id: string) => `/api/hr/employees/${id}`,
  EMPLOYEE_DEACTIVATE: (id: string) => `/api/hr/employees/${id}/deactivate`,
  HR_DASHBOARD: '/api/hr/dashboard',
  HR_DEPARTMENTS: '/api/hr/departments',
  HR_DEPARTMENT: (id: string) => `/api/hr/departments/${id}`,
  HR_JOB_ROLES: '/api/hr/job-roles',
  HR_JOB_ROLE: (id: string) => `/api/hr/job-roles/${id}`,
  HR_SHIFTS: '/api/hr/shifts',
  HR_SHIFT: (id: string) => `/api/hr/shifts/${id}`,
  HR_SHIFT_SCHEDULES: '/api/hr/shift-schedules',
  HR_SHIFT_SCHEDULE: (id: string) => `/api/hr/shift-schedules/${id}`,
  HR_SHIFT_SCHEDULE_APPROVE: (id: string) => `/api/hr/shift-schedules/${id}/approve`,
  ATTENDANCE: '/api/hr/attendance',
  ATTENDANCE_APPROVE: (id: string) => `/api/hr/attendance/${id}/approve`,
  LEAVE_REQUESTS: '/api/hr/leave',
  LEAVE_REQUEST: (id: string) => `/api/hr/leave/${id}`,
  LEAVE_APPROVE: (id: string) => `/api/hr/leave/${id}/approve`,
  LEAVE_REJECT: (id: string) => `/api/hr/leave/${id}/reject`,
  HR_PRODUCTION_WORKER_ASSIGNMENTS: '/api/hr/production-worker-assignments',
  HR_PRODUCTION_WORKER_ASSIGNMENT: (id: string) => `/api/hr/production-worker-assignments/${id}`,
  HR_PRODUCTIVITY: '/api/hr/productivity',
  HR_LABOUR_COSTS: '/api/hr/labour-costs',
  HR_LABOUR_COST_APPROVE: (id: string) => `/api/hr/labour-costs/${id}/approve`,
  HR_OVERTIME: '/api/hr/overtime',
  HR_OVERTIME_APPROVE: (id: string) => `/api/hr/overtime/${id}/approve`,
  HR_OVERTIME_REJECT: (id: string) => `/api/hr/overtime/${id}/reject`,
  HR_PAYROLL_PERIODS: '/api/hr/payroll-periods',
  HR_PAYROLL_PERIOD: (id: string) => `/api/hr/payroll-periods/${id}`,
  PAYROLL: '/api/hr/payroll',
  PAYROLL_GENERATE: '/api/hr/payroll/generate',
  PAYROLL_RECORD: (id: string) => `/api/hr/payroll/${id}`,
  PAYROLL_APPROVE: (id: string) => `/api/hr/payroll/${id}/approve`,
  PAYROLL_POST: (id: string) => `/api/hr/payroll/${id}/post`,
  HR_REPORT: (reportType: string) => `/api/hr/reports/${reportType}`,
  HR_EXPORT: (reportType: string) => `/api/hr/export/${reportType}`,
  HR_IMPORT_EMPLOYEES: '/api/hr/import/employees',
  HR_IMPORT_ATTENDANCE: '/api/hr/import/attendance',
  HR_IMPORT_SHIFT_SCHEDULES: '/api/hr/import/shift-schedules',

  MACHINES: '/api/maintenance/machines',
  MACHINE: (id: string) => `/api/maintenance/machines/${id}`,
  MAINTENANCE_SCHEDULES: '/api/maintenance/schedules',
  MAINTENANCE_SCHEDULE: (id: string) => `/api/maintenance/schedules/${id}`,
  MAINTENANCE_COMPLETE: (id: string) => `/api/maintenance/schedules/${id}/complete`,
  BREAKDOWNS: '/api/maintenance/breakdowns',
  BREAKDOWN: (id: string) => `/api/maintenance/breakdowns/${id}`,
  BREAKDOWN_RESOLVE: (id: string) => `/api/maintenance/breakdowns/${id}/resolve`,

  SETTINGS_USERS: '/api/settings/users',
  SETTINGS_USER: (id: string) => `/api/settings/users/${id}`,
  SETTINGS_USER_ACTIVATE: (id: string) => `/api/settings/users/${id}/activate`,
  SETTINGS_USER_DEACTIVATE: (id: string) => `/api/settings/users/${id}/deactivate`,
  SETTINGS_ROLES: '/api/settings/roles',
  SETTINGS_ROLE: (id: string) => `/api/settings/roles/${id}`,
  SETTINGS_ROLE_PERMISSIONS: (id: string) => `/api/settings/roles/${id}/permissions`,
  SETTINGS_PERMISSIONS: '/api/settings/permissions',
  AUDIT_LOGS: '/api/settings/audit-logs',
  NUMBER_SERIES: '/api/settings/number-series',

  REPORTS: '/api/reports',
  TESTING: {
    DASHBOARD: '/api/testing/dashboard',
    TEST_CASES: '/api/testing/test-cases',
    TEST_CASE: (id: string) => `/api/testing/test-cases/${id}`,
    TEST_RUNS: '/api/testing/test-runs',
    TEST_RUN: (id: string) => `/api/testing/test-runs/${id}`,
    BUGS: '/api/testing/bugs',
    BUG: (id: string) => `/api/testing/bugs/${id}`,
    BUG_ASSIGN: (id: string) => `/api/testing/bugs/${id}/assign`,
    BUG_CLOSE: (id: string) => `/api/testing/bugs/${id}/close`,
    BUG_REOPEN: (id: string) => `/api/testing/bugs/${id}/reopen`,
    UAT_SESSIONS: '/api/testing/uat-sessions',
    UAT_SESSION: (id: string) => `/api/testing/uat-sessions/${id}`,
    UAT_SIGN_OFF: (id: string) => `/api/testing/uat-sessions/${id}/sign-off`,
    TRAINING_SESSIONS: '/api/testing/training-sessions',
    TRAINING_SESSION: (id: string) => `/api/testing/training-sessions/${id}`,
    TRAINING_ATTENDANCE: (id: string) => `/api/testing/training-sessions/${id}/attendance`,
    DOCUMENTATION: '/api/testing/documentation',
    DOCUMENT: (id: string) => `/api/testing/documentation/${id}`,
    RELEASE_NOTES: '/api/testing/release-notes',
    RELEASE_NOTE: (id: string) => `/api/testing/release-notes/${id}`,
    HANDOVER_CHECKLIST: '/api/testing/handover-checklist',
    HANDOVER_ITEM: (id: string) => `/api/testing/handover-checklist/${id}`,
    HANDOVER_APPROVE: (id: string) => `/api/testing/handover-checklist/${id}/approve`,
    EXPORT: (reportType: string) => `/api/testing/export/${reportType}`,
  },
  ADMIN: {
    MIGRATION_DASHBOARD: '/api/admin/migration/dashboard',
    MIGRATION_TEMPLATES: '/api/admin/migration/templates',
    MIGRATION_TEMPLATE_DOWNLOAD: (type: string) => `/api/admin/migration/templates/${type}/download`,
    MIGRATION_UPLOAD: '/api/admin/migration/upload',
    MIGRATION_VALIDATE: (batchId: string) => `/api/admin/migration/${batchId}/validate`,
    MIGRATION_APPROVE: (batchId: string) => `/api/admin/migration/${batchId}/approve`,
    MIGRATION_IMPORT: (batchId: string) => `/api/admin/migration/${batchId}/import`,
    MIGRATION_ROLLBACK: (batchId: string) => `/api/admin/migration/${batchId}/rollback`,
    MIGRATION_HISTORY: '/api/admin/migration/history',
    MIGRATION_BATCH: (batchId: string) => `/api/admin/migration/${batchId}`,
    MIGRATION_ERRORS: (batchId: string) => `/api/admin/migration/${batchId}/errors`,
    OPENING_STOCK: '/api/admin/opening-balances/stock',
    OPENING_CUSTOMERS: '/api/admin/opening-balances/customers',
    OPENING_SUPPLIERS: '/api/admin/opening-balances/suppliers',
    OPENING_ACCOUNTS: '/api/admin/opening-balances/accounts',
    OPENING_POST: '/api/admin/opening-balances/post',
    BACKUPS: '/api/admin/backups',
    BACKUPS_RUN: '/api/admin/backups/run',
    BACKUP_LOGS: '/api/admin/backups/logs',
    BACKUPS_RESTORE_TEST: '/api/admin/backups/restore-test',
    BACKUP_RESTORE_TESTS: '/api/admin/backups/restore-tests',
    HEALTH: '/api/admin/health',
    HEALTH_RUN_CHECK: '/api/admin/health/run-check',
    ERROR_LOGS: '/api/admin/error-logs',
    ERROR_LOG_RESOLVE: (id: string) => `/api/admin/error-logs/${id}/resolve`,
    DATA_INTEGRITY: '/api/admin/data-integrity',
    DATA_INTEGRITY_RUN_CHECK: '/api/admin/data-integrity/run-check',
    DATA_INTEGRITY_RESOLVE: (id: string) => `/api/admin/data-integrity/${id}/resolve`,
    DEPLOYMENT_CHECKLIST: '/api/admin/deployment/checklist',
    DEPLOYMENT_CHECKLIST_ITEM: (id: string) => `/api/admin/deployment/checklist/${id}`,
    DEPLOYMENT_READINESS: '/api/admin/deployment/readiness',
    DEPLOYMENT_RUN_READINESS: '/api/admin/deployment/run-readiness-check',
    DEPLOYMENT_REQUEST_GO_LIVE: '/api/admin/deployment/request-go-live',
    DEPLOYMENT_APPROVE_GO_LIVE: '/api/admin/deployment/approve-go-live',
  },

  NOTIFICATIONS: '/api/notifications',
  NOTIFICATION_READ: (id: string) => `/api/notifications/${id}/read`,
  NOTIFICATION_DISMISS: (id: string) => `/api/notifications/${id}/dismiss`,
  NOTIFICATIONS_READ_ALL: '/api/notifications/read-all',
  NOTIFICATIONS_UNREAD: '/api/notifications/unread',
  NOTIFICATIONS_UNREAD_COUNT: '/api/notifications/unread-count',
  NOTIFICATIONS_SETTINGS: '/api/notifications/settings',
  NOTIFICATION_RULES: '/api/notifications/rules',
  NOTIFICATION_RULE: (id: string) => `/api/notifications/rules/${id}`,
  NOTIFICATION_TEMPLATES: '/api/notifications/templates',
  NOTIFICATION_TEMPLATE: (id: string) => `/api/notifications/templates/${id}`,
  NOTIFICATION_PREFERENCES: '/api/notifications/preferences',
  NOTIFICATION_ESCALATION_RULES: '/api/notifications/escalation-rules',
  NOTIFICATION_ESCALATION_RULE: (id: string) => `/api/notifications/escalation-rules/${id}`,
  NOTIFICATION_REMINDER_RULES: '/api/notifications/reminder-rules',
  NOTIFICATION_REMINDER_RULE: (id: string) => `/api/notifications/reminder-rules/${id}`,
  NOTIFICATION_DELIVERY_LOGS: '/api/notifications/delivery-logs',
  NOTIFICATION_ALERT_DASHBOARD: '/api/notifications/alert-dashboard',
  NOTIFICATION_TEST: '/api/notifications/test',

  AUTH,
  PROCUREMENT: {
    DASHBOARD: '/api/procurement/dashboard',
    SUPPLIERS: '/api/procurement/suppliers',
    SUPPLIER: (id: string) => `/api/procurement/suppliers/${id}`,
    SUPPLIER_META: '/api/procurement/suppliers/meta',
    SUPPLIER_ACTIVATE: (id: string) => `/api/procurement/suppliers/${id}/activate`,
    SUPPLIER_DEACTIVATE: (id: string) => `/api/procurement/suppliers/${id}/deactivate`,
    SUPPLIER_UPLOAD_DOCUMENT: '/api/procurement/suppliers/upload',
    SUPPLIER_BALANCE: (id: string) => `/api/procurement/suppliers/${id}/balance`,
    SUPPLIER_HISTORY: (id: string) => `/api/procurement/suppliers/${id}/history`,
    SUPPLIER_STATEMENT: (id: string) => `/api/procurement/suppliers/${id}/statement`,
    SUPPLIER_CATEGORIES: '/api/procurement/supplier-categories',
    REQUISITIONS: '/api/procurement/requisitions',
    REQUISITION: (id: string) => `/api/procurement/requisitions/${id}`,
    PURCHASE_ORDERS: '/api/procurement/purchase-orders',
    PURCHASE_ORDER: (id: string) => `/api/procurement/purchase-orders/${id}`,
    GRNS: '/api/procurement/grns',
    GRN: (id: string) => `/api/procurement/grns/${id}`,
    GOODS_RECEIVING_STATUS: '/api/procurement/goods-receiving-status',
    SUPPLIER_SHORTAGES: '/api/procurement/supplier-shortages',
    SUPPLIER_SHORTAGE: (id: string) => `/api/procurement/supplier-shortages/${id}`,
    SUPPLIER_RETURNS: '/api/procurement/supplier-returns',
    SUPPLIER_RETURN: (id: string) => `/api/procurement/supplier-returns/${id}`,
    SUPPLIER_RETURN_APPROVE: (id: string) => `/api/procurement/supplier-returns/${id}/approve`,
    SUPPLIER_INVOICES: '/api/procurement/supplier-invoices',
    SUPPLIER_INVOICE: (id: string) => `/api/procurement/supplier-invoices/${id}`,
    SUPPLIER_PAYMENTS: '/api/procurement/supplier-payments',
    REPORT_PURCHASE_ORDERS: '/api/procurement/reports/purchase-orders',
    REPORT_SUPPLIER_SHORTAGES: '/api/procurement/reports/supplier-shortages',
    REPORT_SUPPLIER_PERFORMANCE: '/api/procurement/reports/supplier-performance',
    REPORT_INVOICE_AGEING: '/api/procurement/reports/invoice-ageing',
    REPORT_COST_VARIANCE: '/api/procurement/reports/cost-variance',
    EXPORT: (reportType: string) => `/api/procurement/export/${reportType}`,
    IMPORT_SUPPLIERS: '/api/procurement/import/suppliers',
    IMPORT_SUPPLIERS_TEMPLATE: '/api/procurement/import/suppliers/template',
    IMPORT_SUPPLIERS_HISTORY: '/api/procurement/import/suppliers/history',
    IMPORT_SUPPLIERS_ERRORS: (batchId: string) => `/api/procurement/import/suppliers/${batchId}/errors`,
    IMPORT_SUPPLIER_PRICES: '/api/procurement/import/supplier-prices',
    META: '/api/procurement/meta'
  },
  INVENTORY: {
    DASHBOARD: '/api/inventory/dashboard',
    ITEMS: '/api/inventory/items',
    WAREHOUSES: '/api/inventory/warehouses',
    STOCK_BALANCES: '/api/inventory/stock-balances',
    STOCK_MOVEMENTS: '/api/inventory/stock-movements',
    TRANSFERS: '/api/inventory/transfers',
    GOODS_RECEIVED: '/api/inventory/goods-received',
    PRODUCTION_ISSUE: '/api/inventory/production-issue',
    FINISHED_GOODS_RECEIPT: '/api/inventory/finished-goods-receipt',
    SALES_DISPATCH: '/api/inventory/sales-dispatch',
    STOCK_TAKE: '/api/inventory/stock-take',
    GOODS_RETURN: '/api/inventory/goods-return',
    SUPPLIER_SHORTAGES: '/api/inventory/supplier-shortages',
    APPROVALS: '/api/inventory/approvals',
    APPROVAL: (id: string) => `/api/inventory/approvals/${id}`,
    APPROVAL_APPROVE: (id: string) => `/api/inventory/approvals/${id}/approve`,
    APPROVAL_REJECT: (id: string) => `/api/inventory/approvals/${id}/reject`,
    REPORT_STOCK_MOVEMENT: '/api/inventory/reports/stock-movement',
    REPORT_VALUATION: '/api/inventory/reports/valuation',
    REPORT_OPENING_CLOSING: '/api/inventory/reports/opening-closing',
    REPORT_SUPPLIER_SHORTAGES: '/api/inventory/reports/supplier-shortages',
    REPORT_BRANCH_STOCK: '/api/inventory/reports/branch-stock',
    EXPORT: (reportType: string) => `/api/inventory/export/${reportType}`,
    LOW_STOCK: '/api/inventory/low-stock',
    EXPIRING: '/api/inventory/expiring',
    META: '/api/inventory/meta'
  },
  PRODUCTION: {
    DASHBOARD: '/api/production/dashboard',
    PRODUCTS: '/api/production/products',
    PRODUCT: (id: string) => `/api/production/products/${id}`,
    FLAVOURS: '/api/production/flavours',
    CHOCOLATE_TYPES: '/api/production/chocolate-types',
    RECIPES: '/api/production/recipes',
    RECIPE: (id: string) => `/api/production/recipes/${id}`,
    RECIPE_ACTIVATE: (id: string) => `/api/production/recipes/${id}/activate`,
    PLANS: '/api/production/plans',
    PLAN: (id: string) => `/api/production/plans/${id}`,
    PLAN_APPROVE: (id: string) => `/api/production/plans/${id}/approve`,
    PLAN_CANCEL: (id: string) => `/api/production/plans/${id}/cancel`,
    MATERIAL_REQUIREMENTS: (planId: string) => `/api/production/material-requirements/${planId}`,
    BATCHES: '/api/production/batches',
    BATCH: (id: string) => `/api/production/batches/${id}`,
    BATCH_MATERIAL_USAGE: (id: string) => `/api/production/batches/${id}/material-usage`,
    BATCH_OUTPUT: (id: string) => `/api/production/batches/${id}/output`,
    BATCH_QUALITY_CHECK: (id: string) => `/api/production/batches/${id}/quality-check`,
    BATCH_COMPLETE: (id: string) => `/api/production/batches/${id}/complete`,
    BATCH_TRANSFER_FINISHED_GOODS: (id: string) => `/api/production/batches/${id}/transfer-finished-goods`,
    BATCH_REQUEST_MATERIALS: (id: string) => `/api/production/batches/${id}/request-materials`,
    BATCH_APPROVE_MATERIALS: (id: string) => `/api/production/batches/${id}/approve-materials`,
    BATCH_RESERVE: (id: string) => `/api/production/batches/${id}/reserve-materials`,
    BATCH_START: (id: string) => `/api/production/batches/${id}/start`,
    BATCH_SUBMIT_QUALITY: (id: string) => `/api/production/batches/${id}/submit-quality`,
    BATCH_QUALITY: (id: string) => `/api/production/batches/${id}/quality-result`,
    BATCH_CLOSE: (id: string) => `/api/production/batches/${id}/close`,
    BATCH_CANCEL: (id: string) => `/api/production/batches/${id}/cancel`,
    BATCH_ASSIGN_WORKERS: (id: string) => `/api/production/batches/${id}/assign-workers`,
    MATERIAL_REQUESTS: '/api/production/material-requests',
    MATERIAL_REQUEST: (id: string) => `/api/production/material-requests/${id}`,
    MATERIAL_REQUEST_APPROVE: (id: string) => `/api/production/material-requests/${id}/approve`,
    MATERIAL_REQUEST_ISSUE: (id: string) => `/api/production/material-requests/${id}/issue`,
    SHIFTS: '/api/production/shifts',
    SHIFT: (id: string) => `/api/production/shifts/${id}`,
    SHIFT_CLOSE: (id: string) => `/api/production/shifts/${id}/close`,
    SHIFT_TARGETS: '/api/production/shift-targets',
    TRANSFERS: '/api/production/transfers',
    RAW_MATERIAL_TRANSFERS: '/api/production/raw-material-transfers',
    RETURNS_TO_STORES: '/api/production/returns-to-stores',
    WASTAGE: '/api/production/wastage',
    REPORT_PERFORMANCE: '/api/production/reports/performance',
    REPORT_BATCH_PERFORMANCE: '/api/production/reports/batch-performance',
    REPORT_SHIFT_PERFORMANCE: '/api/production/reports/shift-performance',
    REPORT_MATERIAL_CONSUMPTION: '/api/production/reports/material-consumption',
    REPORT_VARIANCE: '/api/production/reports/variance',
    REPORT_YIELD: '/api/production/reports/yield',
    REPORT_PRODUCTIVITY: '/api/production/reports/productivity',
    REPORT_COSTING: '/api/production/reports/costing',
    EXPORT: (reportType: string) => `/api/production/export/${reportType}`,
    IMPORT_RECIPES: '/api/production/import/recipes',
    IMPORT_SHIFT_TARGETS: '/api/production/import/shift-targets',
    META: '/api/production/meta'
  },
  BRANCH_OPERATIONS: {
    SALES: (branchId: string) => `/api/branch-operations/${branchId}/sales`,
    EXPENSES: (branchId: string) => `/api/branch-operations/${branchId}/expenses`,
    SHIFT_CLOSES: (branchId: string) => `/api/branch-operations/${branchId}/shift-closes`,
    SHIFT_CLOSE_DETAIL: (branchId: string, shiftCloseId: string) =>
      `/api/branch-operations/${branchId}/shift-closes/${shiftCloseId}`
  },
  BRANCHES_COMPAT: {
    LIST: '/api/branches',
    DETAIL: (id: string) => `/api/branches/${id}`,
    DASHBOARD: (id: string) => `/api/branches/${id}/dashboard`,
    STOCK: (id: string) => `/api/branches/${id}/stock`,
    USERS: (id: string) => `/api/branches/${id}/users`,
    SHIFTS: (id: string) => `/api/branches/${id}/shifts`,
    SALES: (id: string) => `/api/branches/${id}/sales`,
    CUSTOMERS: (id: string) => `/api/branches/${id}/customers`,
    PAYMENTS: (id: string) => `/api/branches/${id}/payments`,
    EXPENSES: (id: string) => `/api/branches/${id}/expenses`,
    RETURNS: (id: string) => `/api/branches/${id}/returns`,
    REPORT_PROFITABILITY: '/api/branches/reports/profitability'
  },
  SALES: {
    META: '/api/sales/meta',
    CUSTOMERS: '/api/sales/customers',
    CUSTOMER: (id: string) => `/api/sales/customers/${id}`,
    CUSTOMER_ACTIVATE: (id: string) => `/api/sales/customers/${id}/activate`,
    CUSTOMER_DEACTIVATE: (id: string) => `/api/sales/customers/${id}/deactivate`,
    CUSTOMER_BALANCE: (id: string) => `/api/sales/customers/${id}/balance`,
    CUSTOMER_LEDGER: (id: string) => `/api/sales/customers/${id}/ledger`,
    CUSTOMER_GROUPS: '/api/sales/customer-groups',
    PRICES: '/api/sales/prices',
    PRICE: (id: string) => `/api/sales/prices/${id}`,
    DISCOUNTS: '/api/sales/discounts',
    DISCOUNT: (id: string) => `/api/sales/discounts/${id}`,
    DISCOUNT_APPROVE: (id: string) => `/api/sales/discounts/${id}/approve`,
    QUOTATIONS: '/api/sales/quotations',
    QUOTATION: (id: string) => `/api/sales/quotations/${id}`,
    QUOTATION_APPROVE: (id: string) => `/api/sales/quotations/${id}/approve`,
    QUOTATION_CONVERT: (id: string) => `/api/sales/quotations/${id}/convert-to-order`,
    SALES_ORDERS: '/api/sales/orders',
    SALES_ORDER: (id: string) => `/api/sales/orders/${id}`,
    SALES_ORDER_APPROVE: (id: string) => `/api/sales/orders/${id}/approve`,
    SALES_ORDER_CONFIRM: (id: string) => `/api/sales/orders/${id}/confirm`,
    SALES_ORDER_CANCEL: (id: string) => `/api/sales/orders/${id}/cancel`,
    INVOICES: '/api/sales/invoices',
    INVOICE: (id: string) => `/api/sales/invoices/${id}`,
    INVOICE_APPROVE: (id: string) => `/api/sales/invoices/${id}/approve`,
    INVOICE_CANCEL: (id: string) => `/api/sales/invoices/${id}/cancel`,
    INVOICE_PAYMENT: (id: string) => `/api/sales/invoices/${id}/payment`,
    DISPATCHES: '/api/sales/dispatches',
    DISPATCH: (id: string) => `/api/sales/dispatches/${id}`,
    DISPATCH_POST: (id: string) => `/api/sales/dispatches/${id}/post`,
    DISPATCH_CANCEL: (id: string) => `/api/sales/dispatches/${id}/cancel`,
    PAYMENTS: '/api/sales/payments',
    RETURNS: '/api/sales/returns',
    RETURN: (id: string) => `/api/sales/returns/${id}`,
    RETURN_QC: (id: string) => `/api/sales/returns/${id}/qc`,
    RETURN_APPROVE: (id: string) => `/api/sales/returns/${id}/approve`,
    CREDIT_NOTES: '/api/sales/credit-notes',
    CREDIT_NOTE: (id: string) => `/api/sales/credit-notes/${id}`,
    CREDIT_NOTE_APPROVE: (id: string) => `/api/sales/credit-notes/${id}/approve`,
    JOURNALS: '/api/sales/journals',
    REPORT_DAILY_SALES: '/api/sales/reports/daily-sales',
    REPORT_CUSTOMER_SALES: '/api/sales/reports/customer-sales',
    REPORT_PRODUCT_SALES: '/api/sales/reports/product-sales',
    REPORT_BRANCH_SALES: '/api/sales/reports/branch-sales',
    REPORT_INVOICE_AGEING: '/api/sales/reports/invoice-ageing',
    REPORT_CREDIT_LIMITS: '/api/sales/reports/credit-limits',
    REPORT_DISPATCHES: '/api/sales/reports/dispatches',
    REPORT_RETURNS: '/api/sales/reports/returns',
    REPORT_JOURNALS: '/api/sales/reports/journals',
    EXPORT: (reportType: string) => `/api/sales/export/${reportType}`,
    IMPORT_CUSTOMERS: '/api/sales/import/customers',
    IMPORT_PRICES: '/api/sales/import/prices',
    IMPORT_CUSTOMER_BALANCES: '/api/sales/import/customer-balances'
  },
  FINANCE: {
    DASHBOARD: '/api/finance/dashboard',
    META: '/api/finance/meta',
    TRANSACTIONS: '/api/finance/transactions',
    JOURNAL_ENTRIES: '/api/finance/journal-entries',
    JOURNAL_ENTRY: (id: string) => `/api/finance/journal-entries/${id}`,
    JOURNAL_POST: (id: string) => `/api/finance/journal-entries/${id}/post`,
    JOURNALS: '/api/finance/journals',
    CHART_OF_ACCOUNTS: '/api/finance/chart-of-accounts',
    FISCAL_PERIODS: '/api/finance/fiscal-periods',
    EXPENSES: '/api/finance/expenses',
    BANK_ACCOUNTS: '/api/finance/bank-accounts',
    BANK_TRANSACTIONS: '/api/finance/bank-transactions',
    CASH: '/api/finance/cash',
    CASH_ACCOUNTS: '/api/finance/cash-accounts',
    PETTY_CASH: '/api/finance/petty-cash',
    PETTY_CASH_APPROVE: (id: string) => `/api/finance/petty-cash/${id}/approve`,
    BUDGETS: '/api/finance/budgets',
    FIXED_ASSETS: '/api/finance/fixed-assets',
    ACCOUNTS_RECEIVABLE: '/api/finance/accounts-receivable',
    ACCOUNTS_PAYABLE: '/api/finance/accounts-payable',
    TAX_CODES: '/api/finance/tax-codes',
    REPORT_TRIAL_BALANCE: '/api/finance/reports/trial-balance',
    REPORT_PROFIT_AND_LOSS: '/api/finance/reports/profit-and-loss',
    REPORT_BALANCE_SHEET: '/api/finance/reports/balance-sheet',
    REPORT_RATIOS: '/api/finance/reports/ratios',
    REPORT_CASH_FLOW: '/api/finance/reports/cash-flow',
    REPORT_GENERAL_LEDGER: '/api/finance/reports/general-ledger',
    REPORT_RECEIVABLES_AGEING: '/api/finance/reports/receivables-ageing',
    REPORT_PAYABLES_AGEING: '/api/finance/reports/payables-ageing',
    REPORT_RECEIVABLES: '/api/finance/reports/receivables',
    REPORT_PAYABLES: '/api/finance/reports/payables',
    REPORT_BUDGET_VARIANCE: '/api/finance/reports/budget-variance',
    REPORT_BRANCH_PROFITABILITY: '/api/finance/reports/branch-profitability',
    REPORT_BRANCH_COSTING: '/api/finance/reports/branch-costing',
    REPORT_PRODUCTION_COSTING: '/api/finance/reports/production-costing',
    REPORT_INVENTORY_VALUATION: '/api/finance/reports/inventory-valuation',
    REPORT_COST_OF_GOODS_SOLD: '/api/finance/reports/cost-of-goods-sold',
    REPORT_TAX: '/api/finance/reports/tax',
    EXPORT: (reportType: string) => `/api/finance/export/${reportType}`,
    IMPORT_CHART_OF_ACCOUNTS: '/api/finance/import/chart-of-accounts',
    IMPORT_BUDGETS: '/api/finance/import/budgets',
    IMPORT_FIXED_ASSETS: '/api/finance/import/fixed-assets',
    IMPORT_BANK_ACCOUNTS: '/api/finance/import/bank-accounts',
    IMPORT_OPENING_BALANCES: '/api/finance/import/opening-balances'
  },
  QUALITY: {
    DASHBOARD: '/api/quality/dashboard',
    INSPECTIONS: '/api/quality/inspections',
    INSPECTION: (id: string) => `/api/quality/inspections/${id}`,
    INSPECTION_SUBMIT: (id: string) => `/api/quality/inspections/${id}/submit`,
    INSPECTION_APPROVE: (id: string) => `/api/quality/inspections/${id}/approve`,
    INSPECTION_REJECT: (id: string) => `/api/quality/inspections/${id}/reject`,
    TEMPLATES: '/api/quality/templates',
    TEMPLATE: (id: string) => `/api/quality/templates/${id}`,
    RAW_MATERIALS: '/api/quality/raw-materials',
    PRODUCTION_BATCHES: '/api/quality/production-batches',
    RETURNS: '/api/quality/returns',
    RETURN: (id: string) => `/api/quality/returns/${id}`,
    RETURN_SUBMIT_QC: (id: string) => `/api/quality/returns/${id}/submit-qc`,
    RETURN_APPROVE: (id: string) => `/api/quality/returns/${id}/approve`,
    RETURN_REJECT: (id: string) => `/api/quality/returns/${id}/reject`,
    RETURN_INSPECTIONS: '/api/quality/return-inspections',
    DAMAGED_GOODS: '/api/quality/damaged-goods',
    DAMAGED_GOODS_APPROVE: (id: string) => `/api/quality/damaged-goods/${id}/approve`,
    EXPIRED_GOODS: '/api/quality/expired-goods',
    EXPIRED_GOODS_APPROVE: (id: string) => `/api/quality/expired-goods/${id}/approve`,
    REUSABLE_STOCK: '/api/quality/reusable-stock',
    REUSABLE_STOCK_APPROVE: (id: string) => `/api/quality/reusable-stock/${id}/approve`,
    WASTE_DISPOSAL: '/api/quality/waste-disposal',
    WASTE_DISPOSAL_APPROVE: (id: string) => `/api/quality/waste-disposal/${id}/approve`,
    REWORK: '/api/quality/rework',
    MARKET_REPORTS: '/api/quality/market-reports',
    MARKET_REPORT: (id: string) => `/api/quality/market-reports/${id}`,
    MARKET_REPORT_SUBMIT: (id: string) => `/api/quality/market-reports/${id}/submit`,
    MARKET_REPORT_REVIEW: (id: string) => `/api/quality/market-reports/${id}/review`,
    REPORT_RAW_MATERIALS: '/api/quality/reports/raw-materials',
    REPORT_PRODUCTION: '/api/quality/reports/production',
    REPORT_RETURNS: '/api/quality/reports/returns',
    REPORT_DAMAGED_GOODS: '/api/quality/reports/damaged-goods',
    REPORT_EXPIRED_GOODS: '/api/quality/reports/expired-goods',
    REPORT_WASTE: '/api/quality/reports/waste',
    REPORT_MARKET: '/api/quality/reports/market',
    REPORT_FINANCIAL_IMPACT: '/api/quality/reports/financial-impact',
    EXPORT: (reportType: string) => `/api/quality/export/${reportType}`,
    IMPORT_TEMPLATES: '/api/quality/import/templates'
  },
  NOTIFICATIONS_COMPAT: {
    LIST: '/api/notifications',
    MARK_READ: (id: string) => `/api/notifications/${id}/read`,
    DISMISS: (id: string) => `/api/notifications/${id}/dismiss`,
    READ_ALL: '/api/notifications/read-all',
    UNREAD: '/api/notifications/unread',
    UNREAD_COUNT: '/api/notifications/unread-count',
    MARK_ALL_READ: '/api/notifications/read-all',
    SETTINGS: '/api/notifications/settings',
    RULES: '/api/notifications/rules',
    TEMPLATES: '/api/notifications/templates',
    PREFERENCES: '/api/notifications/preferences',
    ESCALATION_RULES: '/api/notifications/escalation-rules',
    REMINDER_RULES: '/api/notifications/reminder-rules',
    DELIVERY_LOGS: '/api/notifications/delivery-logs',
    ALERT_DASHBOARD: '/api/notifications/alert-dashboard',
    TEST: '/api/notifications/test',
  },
  REPORTS_COMPAT: {
    LIST: '/api/reports',
    DASHBOARD: '/api/reports/dashboard',
    EXPORT_CSV: '/api/reports/export/csv',
    EXPORT_PDF: '/api/reports/export/pdf'
  },
  SETTINGS: {
    USERS: '/api/settings/users',
    ROLES: '/api/settings/roles',
    PERMISSIONS: '/api/settings/permissions',
    AUDIT_LOGS: '/api/settings/audit-logs',
    OVERVIEW: '/api/settings/overview',
    SUMMARY: '/api/settings/summary'
  },
  WORKFLOWS: {
    DASHBOARD: '/api/workflows/dashboard',
    DEFINITIONS: '/api/workflows/definitions',
    STEPS: '/api/workflows/steps',
    APPROVAL_RULES: '/api/workflows/approval-rules',
    APPROVALS: '/api/workflows/approvals',
    APPROVAL_APPROVE: (id: string) => `/api/workflows/approvals/${id}/approve`,
    APPROVAL_REJECT: (id: string) => `/api/workflows/approvals/${id}/reject`,
    HISTORY: '/api/workflows/history',
    HISTORY_DOCUMENT: (documentType: string, documentId: string) => `/api/workflows/history/${documentType}/${documentId}`,
    POSTING_LOGS: '/api/workflows/posting-logs',
    POST: (documentType: string, documentId: string) => `/api/workflows/post/${documentType}/${documentId}`,
    CORRECTIONS: '/api/workflows/corrections',
    CORRECTION_APPROVE: (id: string) => `/api/workflows/corrections/${id}/approve`,
    CORRECTION_REJECT: (id: string) => `/api/workflows/corrections/${id}/reject`,
    CORRECTION_APPLY: (id: string) => `/api/workflows/corrections/${id}/apply`,
    REVERSALS: '/api/workflows/reversals',
    REVERSAL_APPROVE: (id: string) => `/api/workflows/reversals/${id}/approve`,
    REVERSAL_POST: (id: string) => `/api/workflows/reversals/${id}/post`,
    VOIDS: '/api/workflows/voids',
    VOID_APPROVE: (id: string) => `/api/workflows/voids/${id}/approve`,
    VOID_POST: (id: string) => `/api/workflows/voids/${id}/post`,
    COMMENTS: '/api/workflows/comments',
    COMMENTS_DOCUMENT: (documentType: string, documentId: string) => `/api/workflows/comments/${documentType}/${documentId}`
  },
  SUPPLIERS_COMPAT: {
    LIST: '/api/procurement/suppliers',
    DETAIL: (id: string) => `/api/procurement/suppliers/${id}`,
    META: '/api/procurement/suppliers/meta',
    PURCHASE_HISTORY: (id: string) => `/api/procurement/suppliers/${id}/purchase-history`
  }
} as const;
